CREATE TABLE IF NOT EXISTS products
(
    id    INTEGER PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    price DOUBLE PRECISION NOT NULL
);
CREATE SEQUENCE products_id_seq START WITH 5 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS markets
(
    id    INTEGER PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    address VARCHAR(254) NOT NULL
);
CREATE SEQUENCE markets_id_seq START WITH 4 INCREMENT BY 1;
